ForebAgro/Forebagro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [
                url(r"^$", views.HomePage.as_view(), name="home"),
                url(r"^about-us/$", views.AboutPage.as_view(), name="about"),
                url(r"^contact-us/$", views.ContactPage, name="contact"),
                url(r"^app/", include('accounts.urls', namespace="accounts")),
                url(r"^admin/", admin.site.urls),
                url(r"^accounts/", include("django.contrib.auth.urls")),
                url(r'^clientele/', include("clientele.urls", namespace="clientele")),
                url(r'^contact/', include("contact.urls", namespace="contact")),
                url(r'^transactions/', include("transactions.urls", namespace="transactions")),
                url(r'^products/', include("products.urls", namespace="products")),
                url(r'^constants/', include("constant.urls", namespace="constants")),
]

ForebAgro/clientele/urls.py
from django.conf.urls import url
from . import views

app_name = 'clientele'

urlpatterns = [
                url(r'^clientele/$', views.clientele, name='clientele_list'),
                url(r'^debtor/$', views.debtor, name='clientele_debtor'),
                url(r'^creditor/$', views.creditor, name='clientele_creditor'),
                url(r'^register/$', views.register, name='register_clientele'),
                url(r'^update_clientele/(?P<id>\d+)/$', views.clientele_update, name='update'),
                url(r'^delete_clientele/(?P<pk>\d+)/$', views.ClienteleDeleteView.as_view(), name='delete'),
                #url(r'^id/([0-9]+)/order/add/$', views.add_order, name='add_order'),
                #url(r'^order/save/$', views.save_order, name='save_order'),
                url(r'^csv/$', views.getfile, name='get'),

 ]

ForebAgro/contact/urls.py
from django.conf.urls import url, include, url
from contact import views

urlpatterns = [
    url(r'^contact-us/$', views.send, name='send'),
]

ForebAgro/clientele/models.py
from django.db import models
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm, TextInput, CharField, NumberInput, Select, PasswordInput, ChoiceField
from django.core.validators import MinLengthValidator


# Create your models here.
class Clientele(models.Model):

    clientele_name = models.CharField(max_length=100, unique=True, null=False, help_text="Clientele Name")
    clientele_type = models.CharField(max_length=20, )
    clientele_address = models.CharField(max_length=20, null=True, blank=True)
    clientele_contact_number = models.CharField(max_length=20, blank=True)
    clientele_email = models.EmailField(blank=True)
    clientele_wallet_balance = models.FloatField(max_length=20, null=True, blank=True)
    default_wallet_balance = models.FloatField(default=0, null=True)

    class Meta:
        db_table = "clientele"
        ordering = ('clientele_name',)

    def __str__(self):
        return self.clientele_name


class ClienteleForm(ModelForm):


    class Meta:

        clientele_type = [('', 'SELECT'), ('supplier', 'Supplier'), ('buyer', 'Buyer'), ('both', 'Both'),
                          ('eb-client', 'Expense-Based Client')]
        model = Clientele
        # fields = '__all__' #to include all the fields in the form

        # specify what fields to be included in the form
        fields = ['clientele_name', 'clientele_type', 'clientele_address', 'clientele_email',
                  'clientele_contact_number']

        widgets = {
            'clientele_name': TextInput(attrs={'class': 'form-control'}),
            'clientele_type': Select(attrs={'class': 'form-control'},choices=clientele_type),
            'clientele_address': TextInput(attrs={'class': 'form-control'}),
            'clientele_email': TextInput(attrs={'class': 'form-control'}),
            'clientele_contact_number': NumberInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'clientele_name': _("Clientele Name"),
            'clientele_contact_number': _("Contact Number"),
            'clientele_email': _("Clientele Email"),
            'clientele_wallet_balance': _("Clientele Wallet Balance"),
            'clientele_address': _("Clientele Address"),
            'clientele_type': _("Clientele Type"),
        }

        # help_text ={
        # 	'dealer_name':_("Input the correct dealer name"),
        # 	'dealer_contact_number':_("Contact number must a Globe network"),
        # }

        error_message = {
            'dealer_address': {
                'max_length': _("Address must not exceed 20 characters"),
            }
        }

    # validators = {
    # 	'dealer_address': MinLengthValidator(2)
    # }

ForebAgro/clientele/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse, request
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
import csv
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Clientele, ClienteleForm
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)
from transactions.models import TransactionRecord
from django.core import serializers

# Create your views here.
@login_required
def clientele(request):
    clientele = Clientele.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(clientele, 10)
    try:
        clienteles = paginator.page(page)
    except PageNotAnInteger:
        clienteles = paginator.page(1)
    except EmptyPage:
        clienteles = paginator.page(paginator.num_pages)
    return render(request, 'clientele/clientele_list.html', { 'clienteles': clienteles })


@login_required
def creditor(request):
    d_name = []
    c_name = []
    ids = Clientele.objects.filter().values_list('id', flat=True)
    debtoroutstandingList = []
    creditoroutstandingList = []
    for d in ids:
        qj = TransactionRecord.objects.raw(
            "Select 1 as id, SUM(OUTSTANDING) as outstanding FROM (Select 0 AS TRANSACTION_COST, sales.transaction_income AS INCOME, sales.amount_paid AS AMOUNT_PAID, (sales.amount_paid-sales.transaction_income) AS OUTSTANDING, CASE WHEN (sales.transaction_income-sales.amount_paid) >= 0 " +
            "THEN 'DEBIT' ELSE 'CREDIT'  END AS LEG_TYPE from transactions_record Tr Left join clientele client On Tr.clientele_id= client.id Left Join sales_transactions sales ON Tr.transaction_reference= sales.transaction_reference Where Tr.clientele_id = %s " +
            "and Tr.transaction_status='approved' " +
            "UNION " +
            "Select  PT.transaction_cost AS COST, 0 AS TRANSACTION_INCOME,PT.amount_paid AS AMOUNT_PAID,(PT.transaction_cost-PT.amount_paid) AS OUTSTANDING, CASE WHEN (PT.transaction_cost-PT.amount_paid) >= 0 THEN 'CREDIT' ELSE 'DEBIT'  END AS LEG_TYPE " +
            "from transactions_record Tr Left join clientele client On Tr.clientele_id= client.id Left Join purchase_transactions PT ON Tr.transaction_reference= PT.transaction_reference Where Tr.clientele_id = %s and Tr.transaction_status='approved' " +
            "UNION " +
            "Select  CDT.amount_paid AS COST, 0 AS TRANSACTION_INCOME,CDT.amount_paid AS AMOUNT_PAID,(CDT.amount_paid) AS OUTSTANDING, 'CREDIT' AS LEG_TYPE from transactions_record Tr Left join clientele client On Tr.clientele_id= client.id " +
            "Left Join customer_debt_transactions CDT ON Tr.transaction_reference= CDT.transaction_reference Where Tr.clientele_id = %s  and Tr.transaction_status='approved' " +
            "UNION " +
            "Select  0 AS COST, FDT.amount_paid AS TRANSACTION_INCOME,FDT.amount_paid AS AMOUNT_PAID,(FDT.amount_paid * -1) AS OUTSTANDING, 'DEBIT' AS LEG_TYPE from transactions_record Tr	Left join clientele client " +
            "On Tr.clientele_id= client.id Left Join foreb_debt_transactions FDT ON Tr.transaction_reference= FDT.transaction_reference Where Tr.clientele_id = %s  and Tr.transaction_status='approved')",
            [d, d, d, d])
        customer_names = Clientele.objects.filter(pk=d).values()[0]
        customer_name = customer_names["clientele_name"]

        qjj = list(qj)
        J = []
        for q in qjj:
            if q.outstanding is None:
                J.append(0)
            else:
                J.append(q.outstanding)

            for i in J:
                if i < 0:
                    d_name.append(customer_name)
                    debtoroutstandingList.append(i)
                else:
                    c_name.append(customer_name)
                    creditoroutstandingList.append(i)

    debtors = dict(zip(d_name, debtoroutstandingList))
    creditors = dict(zip(c_name, creditoroutstandingList))
    new_creditor = creditors.items()
    creditor_r = list(new_creditor)

    page = request.GET.get('page', 1)

    paginator = Paginator(creditor_r, 10)
    try:
        creditor = paginator.page(page)
    except PageNotAnInteger:
        creditor = paginator.page(1)
    except EmptyPage:
        creditor = paginator.page(paginator.num_pages)
    print(creditor)
    return render(request, "clientele/creditors.html", {'creditor': creditor})


@login_required
def debtor(request):
    d_name = []
    c_name = []
    ids = Clientele.objects.filter().values_list('id', flat=True)
    debtoroutstandingList = []
    creditoroutstandingList = []
    for d in ids:
        qj = TransactionRecord.objects.raw(
            "Select 1 as id, SUM(OUTSTANDING) as outstanding FROM (Select 0 AS TRANSACTION_COST, sales.transaction_income AS INCOME, sales.amount_paid AS AMOUNT_PAID, (sales.amount_paid-sales.transaction_income) AS OUTSTANDING, CASE WHEN (sales.transaction_income-sales.amount_paid) >= 0 " +
            "THEN 'DEBIT' ELSE 'CREDIT'  END AS LEG_TYPE from transactions_record Tr Left join clientele client On Tr.clientele_id= client.id Left Join sales_transactions sales ON Tr.transaction_reference= sales.transaction_reference Where Tr.clientele_id = %s " +
            "and Tr.transaction_status='approved' " +
            "UNION " +
            "Select  PT.transaction_cost AS COST, 0 AS TRANSACTION_INCOME,PT.amount_paid AS AMOUNT_PAID,(PT.transaction_cost-PT.amount_paid) AS OUTSTANDING, CASE WHEN (PT.transaction_cost-PT.amount_paid) >= 0 THEN 'CREDIT' ELSE 'DEBIT'  END AS LEG_TYPE " +
            "from transactions_record Tr Left join clientele client On Tr.clientele_id= client.id Left Join purchase_transactions PT ON Tr.transaction_reference= PT.transaction_reference Where Tr.clientele_id = %s and Tr.transaction_status='approved' " +
            "UNION " +
            "Select  CDT.amount_paid AS COST, 0 AS TRANSACTION_INCOME,CDT.amount_paid AS AMOUNT_PAID,(CDT.amount_paid) AS OUTSTANDING, 'CREDIT' AS LEG_TYPE from transactions_record Tr Left join clientele client On Tr.clientele_id= client.id " +
            "Left Join customer_debt_transactions CDT ON Tr.transaction_reference= CDT.transaction_reference Where Tr.clientele_id = %s  and Tr.transaction_status='approved' " +
            "UNION " +
            "Select  0 AS COST, FDT.amount_paid AS TRANSACTION_INCOME,FDT.amount_paid AS AMOUNT_PAID,(FDT.amount_paid * -1) AS OUTSTANDING, 'DEBIT' AS LEG_TYPE from transactions_record Tr	Left join clientele client " +
            "On Tr.clientele_id= client.id Left Join foreb_debt_transactions FDT ON Tr.transaction_reference= FDT.transaction_reference Where Tr.clientele_id = %s  and Tr.transaction_status='approved')",
            [d, d, d, d])
        customer_names = Clientele.objects.filter(pk=d).values()[0]
        customer_name = customer_names["clientele_name"]

        qjj = list(qj)
        J = []
        for q in qjj:
            if q.outstanding is None:
                J.append(0)
            else:
                J.append(q.outstanding)

            for i in J:
                if i < 0:
                    d_name.append(customer_name)
                    debtoroutstandingList.append(i)
                else:
                    c_name.append(customer_name)
                    creditoroutstandingList.append(i)

    debtors = dict(zip(d_name, debtoroutstandingList))
    creditors = dict(zip(c_name, creditoroutstandingList))
    new_debtor = debtors.items()
    debtor_r = list(new_debtor)

    page = request.GET.get('page', 1)

    paginator = Paginator(debtor_r, 10)
    try:
        debtor = paginator.page(page)
    except PageNotAnInteger:
        debtor = paginator.page(1)
    except EmptyPage:
        debtor = paginator.page(paginator.num_pages)

    return render(request, "clientele/debtors.html", {'debtor': debtor})

@login_required
def register(request):
    if request.method == 'POST':
        form = ClienteleForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            name = form.cleaned_data['clientele_name']
            obj.clientele_name = name.upper()
            form.save()
            return redirect('/clientele/clientele')
    else:
        form = ClienteleForm()

    return render(request, "clientele/clientele_form.html", {"form": form, "messages": ''})


@login_required
def clientele_update(request, id):
    if request.method == 'POST':
        pro = Clientele.objects.get(id=id)
        form = ClienteleForm(request.POST, instance=pro)
        if form.is_valid():
            form.save()
            return redirect('/clientele/clientele')
    else:

        pro = Clientele.objects.get(id=id)
        form = ClienteleForm(instance=pro)

    return render(request, "clientele/clientele_update.html", {"form": form, "messages": ''})



class ClienteleDeleteView(LoginRequiredMixin, DeleteView):
    model = Clientele
    success_url = reverse_lazy('clientele:clientele_list')

def getfile(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=clientele.csv'
    clientele = Clientele.objects.all()
    writer = csv.writer(response)
    for c in clientele:
        writer.writerow([c.clientele_name, c.clientele_type, c.clientele_address, c.clientele_email,
                         c.clientele_contact_number, c.clientele_wallet_balance])
    return response

ForebAgro/clientele/templates/clientele/clientele_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object }}?</p><br><hr>
    <button type="submit" class="btn btn-danger" value=""><i class="fa fa-check-circle white fa-lg" aria-hidden="true"></i> Confirm</button>
    <a href="{% url 'clientele:clientele_list' %}" class="btn btn-warning"><i class="fa fa-remove fa-lg white" aria-hidden="true"></i> Cancel</a>
</form>
{% endblock %}

ForebAgro/clientele/templates/clientele/clientele_form.html
{% extends "base.html" %}
	
{% block content %}

	<div class="content-wrapper" id="tab">
		<div class="content">
			<div class="head">
				<div class="row">				
					<div class="col-sm-7 title" >
						<span class="fa fa-user"></span>Clientele Registration
					</div>
				</div>
			</div>

			<div class="content padding table-responsive">
				<div class="wrapper">
				<form method="post" autocomplete="off">
					{% csrf_token %}
						{{ form.management_form }}
						{%for field in form%}
							<div class="form-group">
								<label class="form-label">{{field.label}}</label> <small class="text-success">{#field.help_text#}</small>
									{{field.errors}}
								{{field}}
							</div>
						{%endfor%}
					<br><hr>
					<button type="reset" class="btn btn-warning m-sm-right "><i class="fa fa-trash-o white fa-lg" aria-hidden="true"></i> Clear</button>
					<button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o white " aria-hidden="true"></i> Save Info</button>
				</form>
					</div>
			</div>
		</div> <!-- end of content -->
	</div> <!--end of content-wrapper -->
<script type="text/javascript">
		$(document).ready(function(){
			$(".form-control").css({'height': '32px', 'width': '500px'});
			$("#tab").css({'width': '600px', 'margin-left': '70px'});
			$(".wrapper").css({'justify-content': 'center', 'display': 'flex'});
			function showTouched(e){
				alert(e.data.message);
			}
			var proceedmsg = { message: 'Be sure of transaction before proceeding!'};
			$("#proceed").on("mouseover", proceedmsg, showTouched);
		});
</script>
{% endblock content %}

ForebAgro/clientele/templates/clientele/clientele_list.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="content-wrapper">
	<div class="content">
		<div class="head">
			<div class="row">				
				<div class="col-sm-8 title" >
					<span class="fa fa-book"></span>Clientele List
				</div>
				<div class="col-sm-4">
<!--					<form>					-->
<!--						<div class="input-group search-box" style="margin-top:-5px;margin-bottom:-120px">-->
<!--							<input type="text" class="form-control" name="clientele_query" placeholder="Search for clientele">-->
<!--						      <span class="input-group-btn">-->
<!--						        <button class="btn btn-default" type="submit"><i class="fa fa-search fa-fw"></i></button>-->
<!--						      </span>-->
<!--						</div>-->
<!--					</form>-->
				</div>
			</div>
		</div>

		<div class="content padding table-responsive">
			<table class="table table-hover table-condensed w-auto" width="647">
				<thead>
					<tr>
						<th>Name</th>
						<th>Address</th>
						<th>Contact Number</th>
						<th>Customer Type</th>
						<th><center>Actions</center></th>
					</tr>
				</thead>
				<tbody>								
					
					{% for c in clienteles %}
						<tr>
							<td>{{ c.clientele_name }}</td>
							<td>{{ c.clientele_address }}</td>
							<td>{{ c.clientele_contact_number }}</td>
							<td>{{ c.clientele_type }}</td>
							<td class="action-container" align="center">
								{% if perms.clientele.change_clientele %}
								<a  href="{% url 'clientele:update' id=c.id %}" class="btn btn-warning btn-sm" title="Edit Clientele Data">
									<span class="fa fa-edit fa-lg"></span> Edit
								</a>
								{% else %}
								<a class="btn btn-warning btn-sm" title="Edit Clientele Data">
									<span class="fa fa-edit fa-lg"></span> Edit
								</a>
								{% endif %}

								{% if perms.clientele.delete_clientele %}
								<a id="delete-btn" href="{% url 'clientele:delete' pk=c.id %}"  class="btn btn-danger btn-delete" title="Delete Clientele">
									<span class="fa fa-trash-o fa-lg"></span> Delete
								</a>
								{% else %}
								<a href="" id="delete" class="btn btn-danger btn-delete" title="Delete Clientele">
									<span class="fa fa-trash-o fa-lg"></span> Delete
								</a>
								{% endif %}
							</td>
						</tr>
					{%empty%}
					{% endfor %}
				</tbody>
			</table>
			{% if clienteles.has_other_pages %}
  <ul class="pagination">
    {% if clienteles.has_previous %}
      <li><a href="?page={{ clienteles.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in clienteles.paginator.page_range %}
      {% if clienteles.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if clienteles.has_next %}
<li><a href="?page={{ clienteles.next_page_number }}">&raquo;</a></li>    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
		</div>
	</div> <!-- end of content -->

</div> <!--end of content-wrapper -->
<script type="text/javascript">
		$(document).ready(function(){

		});
</script>
{% endblock content %}

ForebAgro/clientele/templates/clientele/clientele_update.html
{% extends "base.html" %}
	
{% block content %}

	<div class="content-wrapper" id="tab">
		<div class="content">
			<div class="head">
				<div class="row">				
					<div class="col-sm-7 title" >
						<span class="fa fa-user"></span>Clientele Update
					</div>
				</div>
			</div>

			<div class="content padding table-responsive">
				<div class="wrapper">
				<form method="post" action="">
					{% csrf_token %}
						{{form.management_form}}
						{%for field in form%}
							<div class="form-group">
								<label class="form-label">{{field.label}}</label> <small class="text-success">{#field.help_text#}</small>
									{{field.errors}}
								{{field}}				
							</div>
						{%endfor%}
					<br><hr>
					<a href="{% url 'clientele:clientele_list' %}" class="btn btn-warning"><i class="fa fa-trash-o white fa-lg" aria-hidden="true"></i> Cancel Update</a>
					<button class="btn btn-primary"><i class="fa fa-floppy-o white " aria-hidden="true"></i> Save Update</button>
				</form>
					</div>
			</div>
		</div> <!-- end of content -->
	</div> <!--end of content-wrapper -->
<script type="text/javascript">
		$(document).ready(function(){
			$(".form-control").css({'height': '32px', 'width': '500px'});
			$("#tab").css({'width': '600px', 'margin-left': '70px'});
			$(".wrapper").css({'justify-content': 'center', 'display': 'flex'});
			function showTouched(e){
				alert(e.data.message);
			}
			var proceedmsg = { message: 'Be sure of transaction before proceeding!'};
			$("#proceed").on("mouseover", proceedmsg, showTouched);
		});
</script>
{% endblock content %}

ForebAgro/clientele/templates/clientele/creditors.html
{% extends "base.html" %}

{% load static %}

{% block javascript %}
{% endblock %}
{% block content %}
{% load humanize %}

<div class="content-wrapper" id="tab">
	<div class="content">
		<div class="head">
			<div class="row">
				<div class="col-sm-8 title" >
					<span class="fa fa-book"></span>Creditors
				</div>
			</div>
		</div>

		<div class="content padding table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Clientele Name</th>
						<th>Wallet Balance</th>
					</tr>
				</thead>
				<tbody>
                    {% for item in creditor %}
                    <tr>
                        <td> {{ item.0 }} </td>
                        <td> &#8358; {{  item.1|stringformat:'0.2f'|intcomma }} </td>
                    </tr>
                    {%empty%}
                        <tr>
							<td colspan="12312" align="center">
								<h1 class="text-danger">No records!</h1>
							</td>
						</tr>
				    {% endfor %}
				</tbody>
			</table>
			{% if creditor.has_other_pages %}
  <ul class="pagination">
    {% if creditor.has_previous %}
      <li><a href="?page={{ creditor.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in creditor.paginator.page_range %}
      {% if creditor.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if creditor.has_next %}
      <li><a href="?page={{ creditor.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
		</div>
	</div> <!-- end of content -->

</div> <!--end of content-wrapper -->
<script type="text/javascript">
		$(document).ready(function(){
		    $("#tab").css({'width': '600px', 'margin-left': '70px'});

		});
</script>
{% endblock content %}

ForebAgro/clientele/templates/clientele/debtors.html
{% extends "base.html" %}

{% load static %}

{% block javascript %}
{% endblock %}
{% block content %}
{% load humanize %}

<div class="content-wrapper" id="tab">
	<div class="content">
		<div class="head">
			<div class="row">
				<div class="col-sm-8 title" >
					<span class="fa fa-book"></span>Debtors
				</div>
			</div>
		</div>

		<div class="content padding table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Clientele Name</th>
						<th>Wallet Balance</th>
					</tr>
				</thead>
				<tbody>
                    {% for item in debtor %}
                    <tr>
                        <td> {{ item.0 }} </td>
                        <td> &#8358; {{  item.1|stringformat:'0.2f'|intcomma }} </td>
                    </tr>
                    {%empty%}
                        <tr>
							<td colspan="12312" align="center">
								<h1 class="text-danger">No records!</h1>
							</td>
						</tr>
				    {% endfor %}
				</tbody>
			</table>
			{% if debtor.has_other_pages %}
			  <ul class="pagination">
				{% if debtor.has_previous %}
				  <li><a href="?page={{ creditor.previous_page_number }}">&laquo;</a></li>
				{% else %}
				  <li class="disabled"><span>&laquo;</span></li>
				{% endif %}
				{% for i in debtor.paginator.page_range %}
				  {% if debtor.number == i %}
					<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
				  {% else %}
					<li><a href="?page={{ i }}">{{ i }}</a></li>
				  {% endif %}
				{% endfor %}
				{% if debtor.has_next %}
				  <li><a href="?page={{ debtor.next_page_number }}">&raquo;</a></li>
				{% else %}
				  <li class="disabled"><span>&raquo;</span></li>
				{% endif %}
			  </ul>
			{% endif %}
		</div>
	</div> <!-- end of content -->

</div> <!--end of content-wrapper -->
<script type="text/javascript">
		$(document).ready(function(){
            $("#tab").css({'width': '600px', 'margin-left': '70px'});
		});
</script>
{% endblock content %}