ForebAgro/Forebagro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [
                url(r"^$", views.HomePage.as_view(), name="home"),
                url(r"^about-us/$", views.AboutPage.as_view(), name="about"),
                url(r"^contact-us/$", views.ContactPage, name="contact"),
                url(r"^app/", include('accounts.urls', namespace="accounts")),
                url(r"^admin/", admin.site.urls),
                url(r"^accounts/", include("django.contrib.auth.urls")),
                url(r'^clientele/', include("clientele.urls", namespace="clientele")),
                url(r'^contact/', include("contact.urls", namespace="contact")),
                url(r'^transactions/', include("transactions.urls", namespace="transactions")),
                url(r'^products/', include("products.urls", namespace="products")),
                url(r'^constants/', include("constant.urls", namespace="constants")),
]

ForebAgro/contact/urls.py
from django.conf.urls import url, include, url
from contact import views

urlpatterns = [
    url(r'^contact-us/$', views.send, name='send'),
]

ForebAgro/transactions/urls.py
from django.conf.urls import url
from . import views

app_name = 'transactions'

urlpatterns = [
                url(r'^record_expense/$', views.record, name='record_expense'),
                url(r'^customer_debt/$', views.customer, name='customer_debt'),
                url(r'^foreb_debt/$', views.foreb, name='foreb_debt'),
                url(r'^purchase/$', views.purchase, name='purchase'),
                url(r'^sales/$', views.sales, name='sales'),

                url(r'^customer_transactions/$', views.showcustomer, name='show_customer'),
                url(r'^foreb_transactions/$', views.showforeb, name='show_foreb'),
                url(r'^sales_transactions/$', views.showsales, name='show_sales'),
                url(r'^purchase_transactions/$', views.showpurchase, name='show_purchase'),
                url(r'^expense_transactions/$', views.showexpense, name='show_expense'),

                url(r'^customer-transactions/$', views.showcustomer_user, name='show_customer_user'),
                url(r'^foreb-transactions/$', views.showforeb_user, name='show_foreb_user'),
                url(r'^sales-transactions/$', views.showsales_user, name='show_sales_user'),
                url(r'^purchase-transactions/$', views.showpurchase_user, name='show_purchase_user'),
                url(r'^expense-transactions/$', views.showexpense_user, name='show_expense_user'),

                url(r'^sales_details/(?P<id>\d+)/$', views.sales_details, name='sales_details'),
                url(r'^purchase_details/(?P<id>\d+)/$', views.purchase_details, name='purchase_details'),
                url(r'^foreb_details/(?P<id>\d+)/$', views.foreb_details, name='foreb_details'),
                url(r'^customer_details/(?P<id>\d+)/$', views.customer_details, name='customer_details'),
                url(r'^expense_details/(?P<id>\d+)/$', views.expense_details, name='expense_details'),

                url(r'^approve_sales/(?P<id>\d+)/$', views.sales_approve, name='approve_sales'),
                url(r'^approve_purchase/(?P<id>\d+)/$', views.purchase_approve, name='approve_purchase'),
                url(r'^approve_foreb/(?P<id>\d+)/$', views.foreb_approve, name='approve_foreb'),
                url(r'^approve_customer/(?P<id>\d+)/$', views.customer_approve, name='approve_customer'),
                url(r'^approve_expense/(?P<id>\d+)/$', views.expense_approve, name='approve_expense'),

                url(r'^view-summary/$', views.view_summary, name='view_summary'),
                url(r'^summary/$', views.summary, name='summary'),
                url(r'^view-customer-statement/$', views.view_customer_statement, name='view_customer_statement'),
                url(r'^customer-statement/$', views.customer_statement, name='customer_statement'),

                url(r'^update-sales/(?P<id>\d+)/$', views.update_sales, name='update_sales'),
                url(r'^update-expense/(?P<id>\d+)/$', views.update_expense, name='update_expense'),
                url(r'^update-purchase/(?P<id>\d+)/$', views.update_purchase, name='update_purchase'),
                url(r'^update-customer/(?P<id>\d+)/$', views.update_customer, name='update_customer'),
                url(r'^update-foreb/(?P<id>\d+)/$', views.update_foreb, name='update_foreb'),

                url(r'^delete-sales/(?P<pk>\d+)/$', views.SalesDeleteView.as_view(), name='delete_sales'),
                url(r'^delete-purchase/(?P<pk>\d+)/$', views.PurchaseDeleteView.as_view(), name='delete_purchase'),
                url(r'^delete-expense/(?P<pk>\d+)/$', views.ExpenseDeleteView.as_view(), name='delete_expense'),
                url(r'^delete-foreb/(?P<pk>\d+)/$', views.ForebDeleteView.as_view(), name='delete_foreb'),
                url(r'^delete-customer/(?P<pk>\d+)/$', views.CustomerDeleteView.as_view(), name='delete_customer'),

                url(r'^homepage/$', views.HomePage.as_view(), name="home"),
]

ForebAgro/transactions/models.py
from django.db import models
from django.db.models import Q
from django.core.validators import validate_comma_separated_integer_list
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm, TextInput, CharField, NumberInput, Select, ChoiceField
from django import forms
from clientele.models import Clientele
from products.models import Product
from django.contrib.admin.widgets import AdminDateWidget


# Create your models here.

class ExpenseBasedTransaction(models.Model):
    date_initiated = models.DateField(max_length=30, null=True)
    clientele_name = models.CharField(max_length=20)
    rate = models.IntegerField(null=True, )
    quantity = models.IntegerField(null=True)
    narration = models.CharField(max_length=100)
    total_cost = models.IntegerField(null=True)
    transaction_reference = models.CharField(max_length=20)
    status = models.CharField(max_length=20)
    original_approved_date = models.DateTimeField(max_length=30, null=True)
    date_approved = models.DateTimeField(max_length=30, null=True)
    transaction_type = models.CharField(max_length=100, null=True)
    clientele_id = models.IntegerField(null=True)
    initiator = models.CharField(max_length=20, null=True, default="admin")
    updated_by = models.CharField(max_length=20, null=True, default="admin")

    class Meta:
        db_table = "expense_based_transactions"

    def __str__(self):
        return self.transaction_reference + " - " + self.clientele_name


eb_main = []


class ExpenseBasedTransactionForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ExpenseBasedTransactionForm, self).__init__(*args, **kwargs)
        clientele_id = Clientele.objects.filter(clientele_type__icontains='eb-client').values_list("id",
                                                                                                   "clientele_name")
        eb_main = []
        for i in clientele_id:
            k = list(i)
            k[0] = str(k[0])
            l = (tuple(k))
            eb_main.append(l)
        eb_mains = [('', 'SELECT')] + eb_main
        self.fields['clientele_id'] = ChoiceField(choices=eb_mains, label='Expensed-Based Client')

    class Meta:
        model = ExpenseBasedTransaction
        # fields = '__all__' #to include all the fields in the form

        # specify what fields to be included in the form
        fields = ['date_initiated', 'clientele_id', 'rate',
                  'quantity', 'total_cost']

        widgets = {
            'date_initiated': AdminDateWidget(),
            'rate': NumberInput(attrs={'class': 'form-control', }),
            'quantity': NumberInput(attrs={'class': 'form-control', }),
            'total_cost': NumberInput(attrs={'class': 'form-control', 'readOnly': True}),
        }

        labels = {
            'date_initiated': _('Date Initiated'),
            'clientele_id': _('Expensed-Based Client'),
            'rate': _('Rate'),
            'quantity': _('Quantity'),
            'total_cost': _('Total Cost'),
        }


class CustomerDebtTransaction(models.Model):
    narration_choice = [('part payment', 'Part Payment of Money Owed'), ('full payment', 'Full Payment of Money Owed')]
    date_initiated = models.DateField(max_length=30, null=True)
    transaction_type = models.CharField(max_length=100, null=True)
    transaction_reference = models.CharField(max_length=20)
    clientele_id = models.IntegerField(null=True)
    clientele_name = models.CharField(max_length=20)
    amount_paid = models.IntegerField(null=True)
    status = models.CharField(max_length=20, null=True)
    narration = models.CharField(max_length=100, choices=narration_choice)
    comments = models.CharField(max_length=100)
    original_approved_date = models.DateTimeField(max_length=30, null=True)
    date_approved = models.DateTimeField(max_length=30, null=True)
    initiator = models.CharField(max_length=20, null=True, default="admin")
    updated_by = models.CharField(max_length=20, null=True, default="admin")

    class Meta:
        db_table = "customer_debt_transactions"

    def __str__(self):
        return self.transaction_reference + " - " + self.clientele_name


cd_main = []


class CustomerDebtTransactionForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(CustomerDebtTransactionForm, self).__init__(*args, **kwargs)
        clientele_id = Clientele.objects.exclude(clientele_type__icontains='eb-client').values_list("id",
                                                                                                    "clientele_name")

        cd_main = []
        for i in clientele_id:
            k = list(i)
            k[0] = str(k[0])
            l = (tuple(k))
            cd_main.append(l)
        cd_mains = [('', 'SELECT')] + cd_main
        self.fields['clientele_name'] = ChoiceField(choices=cd_mains, label='Clientele Name')

    class Meta:
        model = CustomerDebtTransaction
        # fields = '__all__' #to include all the fields in the form

        # specify what fields to be included in the form
        fields = ['date_initiated', 'clientele_name', 'narration', 'comments', 'amount_paid']

        widgets = {
            'amount_paid': NumberInput(attrs={'class': 'form-control'}),
            'narration': Select(attrs={'class': 'form-control'}),
            'comments': TextInput(attrs={'class': 'form-control'}),
            'date_initiated': AdminDateWidget(),
        }

        labels = {
            'date_initiated': _('Date Initiated'),
            'narration': _('Narration'),
            'comments': _('Comments'),
            'amount_paid': _('Amount Paid'),
        }


class ForebDebtTransaction(models.Model):
    narration_choice = [('part payment', 'Part Payment of Money Owed Customer'),
                        ('full payment', 'Full Payment of Money Owed Customer')]

    date_initiated = models.DateField(max_length=30, null=True)
    transaction_type = models.CharField(max_length=100, null=True)
    transaction_reference = models.CharField(max_length=20)
    clientele_id = models.IntegerField(null=True)
    clientele_name = models.CharField(max_length=20)
    amount_paid = models.IntegerField(null=True)
    status = models.CharField(max_length=20, null=True)
    narration = models.CharField(max_length=100, choices=narration_choice)
    comments = models.CharField(max_length=100)
    original_approved_date = models.DateTimeField(max_length=30, null=True)
    date_approved = models.DateTimeField(max_length=30, null=True)
    initiator = models.CharField(max_length=20, null=True, default="admin")
    updated_by = models.CharField(max_length=20, null=True, default="admin")

    class Meta:
        db_table = "foreb_debt_transactions"

    def __str__(self):
        return self.transaction_reference + " - " + self.clientele_name


fd_main = []


class ForebDebtTransactionForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ForebDebtTransactionForm, self).__init__(*args, **kwargs)
        clientele_id = Clientele.objects.exclude(clientele_type__icontains='eb-client').values_list("id",
                                                                                                    "clientele_name")

        fd_main = []
        for i in clientele_id:
            k = list(i)
            k[0] = str(k[0])
            l = (tuple(k))
            fd_main.append(l)
        fd_mains = [('', 'SELECT')] + fd_main
        self.fields['clientele_name'] = ChoiceField(choices=fd_mains, label='Clientele Name')

    class Meta:
        model = ForebDebtTransaction
        # fields = '__all__' #to include all the fields in the form

        # specify what fields to be included in the form
        fields = ['date_initiated', 'clientele_name', 'narration', 'comments', 'amount_paid']

        widgets = {
            'amount_paid': NumberInput(attrs={'class': 'form-control'}),
            'narration': Select(attrs={'class': 'form-control'}),
            'comments': TextInput(attrs={'class': 'form-control'}),
            'date_initiated': AdminDateWidget(),
        }

        labels = {
            'date_initiated': _('Date Initiated'),
            'narration': _('Narration'),
            'comments': _('Comments'),
            'amount_paid': _('Amount Paid'),
        }


class PurchaseTransaction(models.Model):
    date_initiated = models.DateField(max_length=30, null=True)
    transaction_type = models.CharField(max_length=100, null=True)
    transaction_reference = models.CharField(max_length=20, null=True)
    clientele_id = models.IntegerField(null=True, )
    clientele_name = models.CharField(max_length=100)
    product_id = models.IntegerField(null=True)
    product_name = models.CharField(max_length=100)
    narration = models.CharField(max_length=100)
    product_quantity = models.IntegerField(null=True)
    product_discount = models.IntegerField(null=True, blank=True)
    product_rate = models.IntegerField(null=True)
    deductions = models.IntegerField(null=True, blank=True)
    quantity_value = models.IntegerField(null=True)
    expected_oil = models.FloatField(null=True, blank=True)
    expected_cake = models.FloatField(null=True, blank=True)
    cake_value = models.FloatField(null=True, blank=True)
    diesel_rate = models.IntegerField(null=True, blank=True)
    diesel_litres = models.IntegerField(null=True, blank=True)
    diesel_value = models.IntegerField(null=True, blank=True)
    gen_diesel_litres = models.IntegerField(null=True, blank=True)
    gen_diesel_rate = models.IntegerField(null=True, blank=True)
    gen_diesel_value = models.IntegerField(null=True, blank=True)
    other_costs = models.FloatField(null=True, blank=True)
    transaction_income = models.IntegerField(null=True)
    transaction_cost = models.IntegerField(null=True)
    waybill_number = models.IntegerField(null=True, blank=True)
    amount_paid = models.IntegerField(null=True, )

ForebAgro/transactions/templates/transactions/approve_customer.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load humanize %}
{% block content %}

	{% csrf_token %}
	<div class="content-wrapper" id="tab">
		<div name="content">
			<div class="head">
				<div class="row">
					<div class="col-sm-7 title" >
						<span class="fa fa-info-circle"></span>Transaction Details
					</div>
				</div>
			</div>
			<div class="content padding table-responsive" id="wrapper">
				<table class="transaction-detail">
					<tr>
						<th width="150px"><h4><span class="label label-primary">Clientele Name</span></h4></th>
						<td><strong>: {{transactions.clientele_name}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Transaction Ref.</span></h4></th>
						<td><strong>: {{transactions.transaction_reference}}</strong></td>
					</tr>
					{% if transactions.amount_paid %}
					<tr>
						<th><h4><span class="label label-primary">Amount Paid</span></h4></th>
						<td><strong>: &#8358; {{transactions.amount_paid|stringformat:'0.2f'|intcomma}}</strong></td>
					</tr>
					{% else %}
					<tr>
						<th><h4><span class="label label-primary">Amount Paid</span></h4></th>
						<td><strong>: </strong></td>
					</tr>
					{% endif %}

					<tr>
						<th><h4><span class="label label-primary">narration</span></h4></th>
						<td><strong>: {{transactions.narration}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Comments</span></h4></th>
						<td><strong>: {{transactions.comments}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Date Initiated</span></h4></th>
						<td><strong>: {{transactions.date_initiated}}</strong></td>
					</tr>
				</table>
				<br><br><hr>
					<a href="{% url 'transactions:show_customer' %}" class="btn btn-danger"><i class="fa fa-remove fa-lg white" aria-hidden="true"></i> Reject</a>
					{% if perms.transactions.change_customerdebttransaction %}
					<a href="{% url 'transactions:approve_customer' id=transactions.id %}" class="btn btn-primary"><i class="fa fa-check-circle white fa-lg" aria-hidden="true"></i> Approve</a>
					{% else %}
					<a id="approve" href="" class="btn btn-primary"><i class="fa fa-check-circle white fa-lg" aria-hidden="true"></i> Approve</a>
					{% endif %}
			</div>
		</div> <!-- end of content -->
	</div> <!--end of content-wrapper -->

<script type="text/javascript">
		$(document).ready(function(){
			$(".form-control").css({'height': '32px', 'width': '500px'});
			$("#tab").css({'width': '750px', 'margin-left': '70px'});
			$(".wrapper").css({'justify-content': 'center', 'display': 'flex'});
			$("th").css({'font-size': '20px'});
			function showTouched(e){
				alert(e.data.message);
			}
			var approvemsg = { message: 'You are not authorized to make this action!'};
			$("#approve").on("click", approvemsg, showTouched);
			});
</script>
{% endblock content %}

ForebAgro/transactions/templates/transactions/cd_transaction_successful.html
{% extends "base.html" %}

{% block content %}

	<div class="content-wrapper" id="tab">
		<div class="content">
			<div class="head">
				<div class="row">
					<div class="col-sm-7 title" >
						<span class="fa fa-pencil"></span>Record An Expense
					</div>
				</div>
			</div>

			<div class="content padding table-responsive">
		            <div class="jumbotron">
						<p><em>Transaction Successful!</em>&nbsp;&nbsp;<i style="color:#E11B1B" class="fa fa-thumbs-up fa-lg"></i></i></p>
                        <br><hr>
                        <a href="{% url 'transactions:customer_debt' %}" class="btn btn-primary btn-sm" role="button">click here to make another transaction</a>
                    </div>
			</div>
		</div> <!-- end of content -->
	</div> <!--end of content-wrapper -->
<script type="text/javascript">
		$(document).ready(function(){
			$("#tab").css({'width': '600px', 'margin-left': '70px'});
		});
</script>
{% endblock content %}

ForebAgro/transactions/templates/transactions/eb_transaction_form.html
{% extends "base.html" %}
{% load bootstrap3%}
{% block content %}
	<div class="content-wrapper" id="tab">
		<div class="content">
			<div class="head">
				<div class="row">
					<div class="col-sm-7 title" >

						<span><i class="fa fa-pencil"></i> Record An Expense</span>
					</div>
					</div>
				</div>
			<div class="content padding table-responsive" >
				<div class="wrapper">
					<form method="post" >
					{% csrf_token %}
					{% bootstrap_form form %}
					<hr>
					<button type="reset" class="btn btn-warning m-sm-right"><i class="fa fa-trash-o fa-lg white" aria-hidden="true"></i> Clear</button>
					<button id="proceed" class="btn btn-primary m-sm-right">Proceed <i class="fa fa-arrow-circle-right fa-lg white" aria-hidden="true"></i></button>
					</form>
				</div>
			</div>
		</div> <!-- end of content -->
	</div> <!--end of content-wrapper -->
<script type="text/javascript">
			$(document).ready(function(){
				$('#id_quantity, #id_rate').on('input',function(e){
					const quantity = parseInt($('#id_quantity').val()) || 0;
					const rate = parseInt($('#id_rate').val()) || 0;
					const total_cost = rate * quantity;
					$('#id_total_cost').val(total_cost);
				});
				$(".form-control").css({'height': '32px', 'width': '500px'});
				$("#tab").css({'width': '600px', 'margin-left': '70px'});
				$(".wrapper").css({'justify-content': 'center', 'display': 'flex'});
			});
</script>
{% endblock content %}

ForebAgro/transactions/templates/transactions/purchase_list_user.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}
{% block javascript %}
{% endblock %}
{% block content %}

<div class="content-wrapper">
	<div class="content">
		<div class="head">
			<div class="row">
				<div class="col-sm-8 title" >
					<span class="fa fa-book"></span>Purchase Transaction List
				</div>
				<div class="col-sm-4">
					<form>
						<div class="input-group search-box" style="margin-top:-5px;margin-bottom:-120px">
							<input type="text" class="form-control" name="transaction_query" placeholder="Search for Transaction">
						      <span class="input-group-btn">
						        <button class="btn btn-default" type="submit"><i class="fa fa-search fa-fw"></i></button>
						      </span>
						</div>
					</form>
				</div>
			</div>
		</div>

		<div class="content padding table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Clientele Name</th>
						<th>Transaction Cost</th>
						<th>Narration</th>
						<th>Status</th>
						<th><center>Actions</center></th>
					</tr>
				</thead>
				<tbody>

					{% for t in transactions %}
						<tr>
							<td><b>{{forloop.counter}}</b>. {{ t.clientele_name }}</td>
							<td>&#8358; {{ t.transaction_cost|stringformat:"0.2f"|intcomma }}</td>
							<td>{{ t.narration }}</td>
							<td>{{ t.status }}</td>
							<td class="action-container" align="center">

								<a href="{% url 'transactions:update_purchase' id=t.id %}"  class="btn btn-warning btn-sm action" title="View Transaction">
									<span class=""></span> Update|Edit
								</a>
								{% if perms.transactions.delete_purchasetransaction %}
								<a href="{% url 'transactions:delete_purchase' pk=t.id %}"  class="btn btn-danger btn-sm action" title="Delete Clientele">
									<span class="fa fa-trash-o fa-lg"></span> Delete
								</a>
								{% else %}
								<a href="" id="delete" class="btn btn-danger btn-sm action" title="Delete Clientele">
									<span class="fa fa-trash-o fa-lg"></span> Delete
								</a>
								{% endif %}
							</td>
						</tr>
					{%empty%}
						<tr>
							<td colspan="12312" align="center">
								<h1 class="text-danger">No pending transactions!</h1>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div> <!-- end of content -->
</div> <!--end of content-wrapper -->
{% endblock content %}

ForebAgro/transactions/templates/transactions/sa_transaction_form.html
{% extends "base.html" %}
{% load bootstrap3%}
{% block content %}
	<div class="content-wrapper" id="tab">
		<div class="content">
			<div class="head">
				<div class="row">
					<div class="col-sm-7 title" >
						<span><i class="fa fa-pencil"></i> Sales Transaction</span>
					</div>
					<div>
						{% include "includes/sales_tab.html" %}
					</div>
					</div>
				</div>
			<div class="content padding table-responsive">
				<div class="wrapper">
				<form class="" method="post">
					<input type="hidden" value={{expectedoil}} id="expected_oil">
					<input type="hidden" value={{expectedcake}} id="expected_cake">
					<input type="hidden" value={{cakevalue}} id="cake_value">
					<input type="hidden" value={{oilvalue}} id="oil_value">
					{% csrf_token %}
                    {% bootstrap_form form %}
                    <hr>
					<button type="reset" class="btn btn-warning m-sm-right"><i class="fa fa-trash-o fa-lg white" aria-hidden="true"></i> Clear</button>
					<button id="proceed" class="btn btn-primary m-sm-right">Proceed <i class="fa fa-arrow-circle-right fa-lg white " aria-hidden="true"></i></button>				</form>
				</div>
			</div>
		</div> <!-- end of content -->
		<button id="cost" onclick="myFunction()" class="btn btn-success btn-sm">Compute transaction cost <i class="" aria-hidden="true"></i></button>
	</div> <!--end of content-wrapper -->
<!--script for compute transaction button-->
<script>
	function myFunction() {
					var a =document.getElementById('id_quantity_value').value || 0;
					var b =document.getElementById('id_gen_diesel_value').value || 0;
					var c =document.getElementById('id_diesel_value').value || 0;
					var d =document.getElementById('id_other_costs').value || 0;
					var e = parseFloat(b) + parseFloat(c) + parseFloat(d)
					var f = parseFloat(a)
					document.getElementById('id_transaction_cost').value = Math.round(e);
					document.getElementById('id_transaction_income').value = Math.round(f);
				}
</script>


<script type="text/javascript">
			$(document).ready(function(){

				//script Quantity value and transaction income

				//script gen diesel value
				$('#id_gen_diesel_rate, #id_gen_diesel_litres').on('input',function(e){
					const gen_diesel_litres = parseInt($('#id_gen_diesel_litres').val()) || 0;
					const gen_diesel_rate = parseInt($('#id_gen_diesel_rate').val()) || 0;
					const gen_diesel_value = (gen_diesel_litres * gen_diesel_rate);
					$('#id_gen_diesel_value').val(gen_diesel_value);
				});

				//script diesel value
				$('#id_diesel_rate, #id_diesel_litres').on('input',function(e){
					const diesel_litres = parseInt($('#id_diesel_litres').val()) || 0;
					const diesel_rate = parseInt($('#id_diesel_rate').val()) || 0;
					const diesel_value = (diesel_litres * diesel_rate);
					$('#id_diesel_value').val(diesel_value);
				});


				$('#id_product_quantity, #id_product_discount,#id_product_name,#id_product_rate').on('input',function(e){
					var p_name = ($('#id_product_name').val());
					if(p_name==3){
					const product_quantity = parseFloat($('#id_product_quantity').val()) || 0;
					const product_discount = parseFloat($('#id_product_discount').val()) || 0;
					const expectedoil = parseFloat($('#expected_oil').val()) || 0;
					const expected_oil = ((product_quantity - product_discount) / expectedoil)
					$('#id_expected_oil').val(expected_oil);
					} else if(p_name==1){
					const product_quantity = parseFloat($('#id_product_quantity').val()) || 0;
					const product_discount = parseFloat($('#id_product_discount').val()) || 0;
					const expectedoil = parseFloat($('#expected_oil').val()) || 0;
					const expected_oil = 0 - (product_quantity - product_discount)
					$('#id_expected_oil').val(expected_oil);
					}
					else{
					const expected_oil = 0
					$('#id_expected_oil').val(expected_oil);
					}

				});


				$('#id_product_quantity, #id_product_discount,#id_product_name,#id_product_rate, #id_deductions').on('input',function(e){
				var p_name = ($('#id_product_name').val());
				if(p_name==1){
					const product_quantity = parseInt($('#id_product_quantity').val()) || 0;
					const product_discount = parseInt($('#id_product_discount').val()) || 0;
					const product_rate = parseFloat($('#id_product_rate').val()) || 0;
					const deductions = parseFloat($('#id_deductions').val()) || 0;
					const oilvalue = parseFloat($('#oil_value').val()) || 0;
					const quantity_value =  (((product_quantity - product_discount) * product_rate * oilvalue) - deductions);
					const expected_cake = 0;
					const cake_value = 0;
					$('#id_cake_value').val(cake_value);
					$('#id_expected_cake').val(expected_cake);
					$('#id_quantity_value').val(quantity_value);
					}
				else if (p_name==2){
					const product_quantity = parseInt($('#id_product_quantity').val()) || 0;
					const product_discount = parseInt($('#id_product_discount').val()) || 0;
					const product_rate = parseFloat($('#id_product_rate').val()) || 0;
					const deductions = parseFloat($('#id_deductions').val()) || 0;
					const oilvalue = parseFloat($('#oil_value').val()) || 0;
					const expected_cakes = -(product_quantity - product_discount)
					const quantity_value =  (((product_quantity - product_discount) * product_rate) - deductions);
					const expected_cake = parseFloat($('#id_expected_cake').val()) || 0;
				    const cake_values = -(+ expected_cake * 30000);
					$('#id_cake_value').val(Math.round(cake_values));
					$('#id_expected_cake').val(expected_cakes);
					$('#id_quantity_value').val(quantity_value);

				}else{
					const expected_cake = 0;
					$('#id_expected_cake').val(expected_cake);
					}
				});
				$(".form-control").css({'height': '32px', 'width': '500px'});
				$("#tab").css({'width': '600px', 'margin-left': '70px'});
				$("#cost").css({'width': '165px','height': '31px', 'font-size': '12px','margin-left': '50px', 'margin-bottom': '10px' });
				$(".wrapper").css({'justify-content': 'center', 'display': 'flex'});
			});
</script>
{% endblock content %}