ForebAgro/Forebagro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [
                url(r"^$", views.HomePage.as_view(), name="home"),
                url(r"^about-us/$", views.AboutPage.as_view(), name="about"),
                url(r"^contact-us/$", views.ContactPage, name="contact"),
                url(r"^app/", include('accounts.urls', namespace="accounts")),
                url(r"^admin/", admin.site.urls),
                url(r"^accounts/", include("django.contrib.auth.urls")),
                url(r'^clientele/', include("clientele.urls", namespace="clientele")),
                url(r'^contact/', include("contact.urls", namespace="contact")),
                url(r'^transactions/', include("transactions.urls", namespace="transactions")),
                url(r'^products/', include("products.urls", namespace="products")),
                url(r'^constants/', include("constant.urls", namespace="constants")),
]

ForebAgro/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [

    url(r"^$", auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r"logout/$", auth_views.logout, name="logout"),
    url(r'^add_new_user/$', views.add_new_user, name='add_new_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^list/$', views.user_list, name='user_list'),
    #url(r'^delete_user/(?P<pk>\d+)/$', views.UserDeleteView.as_view(), name='delete'),
    url(r'^password-change/(?P<id>\d+)/$', views.password_change, name='password_change'),
    #url(r'^password_change/done/(?P<id>\d+)/$', views.change_password, name='password_change_done'),


]

ForebAgro/clientele/urls.py
from django.conf.urls import url
from . import views

app_name = 'clientele'

urlpatterns = [
                url(r'^clientele/$', views.clientele, name='clientele_list'),
                url(r'^debtor/$', views.debtor, name='clientele_debtor'),
                url(r'^creditor/$', views.creditor, name='clientele_creditor'),
                url(r'^register/$', views.register, name='register_clientele'),
                url(r'^update_clientele/(?P<id>\d+)/$', views.clientele_update, name='update'),
                url(r'^delete_clientele/(?P<pk>\d+)/$', views.ClienteleDeleteView.as_view(), name='delete'),
                #url(r'^id/([0-9]+)/order/add/$', views.add_order, name='add_order'),
                #url(r'^order/save/$', views.save_order, name='save_order'),
                url(r'^csv/$', views.getfile, name='get'),

 ]

ForebAgro/constant/urls.py
from django.conf.urls import url, include, url
from constant import views

urlpatterns = [
    url(r'^add_constant/$', views.add, name='add'),
    url(r'^constant_list/$', views.list, name='list'),
    url(r'^update/(?P<id>\d+)/$', views.update, name='update'),
]

ForebAgro/contact/urls.py
from django.conf.urls import url, include, url
from contact import views

urlpatterns = [
    url(r'^contact-us/$', views.send, name='send'),
]

ForebAgro/transactions/urls.py
from django.conf.urls import url
from . import views

app_name = 'transactions'

urlpatterns = [
                url(r'^record_expense/$', views.record, name='record_expense'),
                url(r'^customer_debt/$', views.customer, name='customer_debt'),
                url(r'^foreb_debt/$', views.foreb, name='foreb_debt'),
                url(r'^purchase/$', views.purchase, name='purchase'),
                url(r'^sales/$', views.sales, name='sales'),

                url(r'^customer_transactions/$', views.showcustomer, name='show_customer'),
                url(r'^foreb_transactions/$', views.showforeb, name='show_foreb'),
                url(r'^sales_transactions/$', views.showsales, name='show_sales'),
                url(r'^purchase_transactions/$', views.showpurchase, name='show_purchase'),
                url(r'^expense_transactions/$', views.showexpense, name='show_expense'),

                url(r'^customer-transactions/$', views.showcustomer_user, name='show_customer_user'),
                url(r'^foreb-transactions/$', views.showforeb_user, name='show_foreb_user'),
                url(r'^sales-transactions/$', views.showsales_user, name='show_sales_user'),
                url(r'^purchase-transactions/$', views.showpurchase_user, name='show_purchase_user'),
                url(r'^expense-transactions/$', views.showexpense_user, name='show_expense_user'),

                url(r'^sales_details/(?P<id>\d+)/$', views.sales_details, name='sales_details'),
                url(r'^purchase_details/(?P<id>\d+)/$', views.purchase_details, name='purchase_details'),
                url(r'^foreb_details/(?P<id>\d+)/$', views.foreb_details, name='foreb_details'),
                url(r'^customer_details/(?P<id>\d+)/$', views.customer_details, name='customer_details'),
                url(r'^expense_details/(?P<id>\d+)/$', views.expense_details, name='expense_details'),

                url(r'^approve_sales/(?P<id>\d+)/$', views.sales_approve, name='approve_sales'),
                url(r'^approve_purchase/(?P<id>\d+)/$', views.purchase_approve, name='approve_purchase'),
                url(r'^approve_foreb/(?P<id>\d+)/$', views.foreb_approve, name='approve_foreb'),
                url(r'^approve_customer/(?P<id>\d+)/$', views.customer_approve, name='approve_customer'),
                url(r'^approve_expense/(?P<id>\d+)/$', views.expense_approve, name='approve_expense'),

                url(r'^view-summary/$', views.view_summary, name='view_summary'),
                url(r'^summary/$', views.summary, name='summary'),
                url(r'^view-customer-statement/$', views.view_customer_statement, name='view_customer_statement'),
                url(r'^customer-statement/$', views.customer_statement, name='customer_statement'),

                url(r'^update-sales/(?P<id>\d+)/$', views.update_sales, name='update_sales'),
                url(r'^update-expense/(?P<id>\d+)/$', views.update_expense, name='update_expense'),
                url(r'^update-purchase/(?P<id>\d+)/$', views.update_purchase, name='update_purchase'),
                url(r'^update-customer/(?P<id>\d+)/$', views.update_customer, name='update_customer'),
                url(r'^update-foreb/(?P<id>\d+)/$', views.update_foreb, name='update_foreb'),

                url(r'^delete-sales/(?P<pk>\d+)/$', views.SalesDeleteView.as_view(), name='delete_sales'),
                url(r'^delete-purchase/(?P<pk>\d+)/$', views.PurchaseDeleteView.as_view(), name='delete_purchase'),
                url(r'^delete-expense/(?P<pk>\d+)/$', views.ExpenseDeleteView.as_view(), name='delete_expense'),
                url(r'^delete-foreb/(?P<pk>\d+)/$', views.ForebDeleteView.as_view(), name='delete_foreb'),
                url(r'^delete-customer/(?P<pk>\d+)/$', views.CustomerDeleteView.as_view(), name='delete_customer'),

                url(r'^homepage/$', views.HomePage.as_view(), name="home"),
]

ForebAgro/contact/models.py
from django.db import models
from django.forms import ModelForm, NumberInput, Select, TextInput, Textarea
from django.utils.translation import ugettext_lazy as _


class Contact(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField(blank=False)
    message = models.TextField(max_length=250)

    class Meta:
        db_table = "contact"

    def __str__(self):
        return self.full_name


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'email', 'message']

        widgets = {
            'full_name': TextInput(attrs={'class': 'form-control'}),
            'email': TextInput(attrs={'class': 'form-control'}),
            'message': Textarea(attrs={'class': 'form-control',"style": "resize: none"}),
        }

        labels = {
            'full_name': _("Full Name"),
            'email': _("Email"),
            'message': _("Message")
        }

ForebAgro/contact/views.py
from django.shortcuts import render, redirect,HttpResponseRedirect , get_object_or_404
from django.views.generic import TemplateView
from .models import Contact, ContactForm
from django.contrib import messages

# Create your views here.
def send(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Message Sent')
            return redirect('/contact-us')
    else:
        form = ContactForm()

    return render(request, "contact.html", {"form": form, "messages": 'messages'})

ForebAgro/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap3 %}
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Forebagro</title>
	<link rel="short icon" type="image/png" href="{% static 'images/favicon.png' %}" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i"/>
	<link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@1,400;1,500&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Recursive:wght@500&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
    <!--date picker css and javascript-->
	<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>
	<script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/actions.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/calendar.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>

	<script type="text/javascript">
		$(document).ready(function(){
			$("#button").css({'background-color': 'grey', 'height': '34px','margin-top': '-1px', 'border':'none', 'border-radius':'10px'});
			$(".white").css({'color': 'white',});welcome
			$("#welcome").css({'color': 'white', 'font-weight':'bolder',  });
			$("#white").css({'color': 'black',  });
			$("#whit").css({'color': 'black',  });
			var dt = new Date();
			document.getElementById("datetime").innerHTML=dt.toLocaleString();
		});
</script>

</head>

<body>
	<section class="body">
	<div  class="container-fluid">
		<div class="row no-gutters" style="margin-left:-15px;position: relative;margin-right:-15px ">
			<div class="col-sm-3 col col-left">
				<div class="content">
					<div class="project-title">
						<div class="nav-logo">
							<a href="{% url 'transactions:home' %}"><img src= "{% static 'images/foreblogo1.png' %}" class="user"></a>
						</div>
<!--						<div class="nav-title">-->
<!--							<h4 id="foreb">Forebagro Ltd.</h4>-->
<!--						</div>-->
					</div>

					<ul class="side-nav">
						<li>
							<a ><span class="fa fa-dashboard icon"></span>User Management</a>
							<ul class="nav nav-pills nav-stacked">
								{% if perms.user.add_user %}
								<li class="active"><a href="{% url 'accounts:add_new_user' %}">Add New User <br><small id="whit">Authorized user only</small></a></li>
								{% else %}
								<li class="active"><a href="">Add New User<i class="fa fa-lock fa-lg white pull-right" aria-hidden="true"></i><br><small id="white">Authorized user only</small></a></li>
								{% endif %}
								<li class="active"><a href="{% url 'accounts:password_change' id=user.id %}">Change Password</a></li>
							</ul>
						</li>

						<li>
							<a href="{% url 'clientele:clientele_list' %}"><span class="fa fa-user icon"></span>Clientele</a>
                            <ul class="nav nav-pills nav-stacked">
								<li class="active"><a href="{% url 'clientele:clientele_list' %}">All Clientele</a></li>
								<li class="active"><a href="{% url 'clientele:register_clientele' %}">Add New Clientele</a></li>
								<li class="active"><a href="{% url 'clientele:clientele_creditor' %}">All Creditors</a></li>
								<li class="active"><a href="{% url 'clientele:clientele_debtor' %}">All Debtors</a></li>
							</ul>
						</li>

                        <li>
							<a><span><i class="fa fa-briefcase icon"></i></span>Transactions</a>
							<ul class="nav nav-pills nav-stacked" id="roo">
								<li class="active"><a href="{% url 'transactions:sales' %}">Sales Transactions</a></li>
								<li class="active"><a href="{% url 'transactions:purchase' %}">Purchase Transactions</a></li>
								<li class="active"><a href="{% url 'transactions:record_expense' %}">Record An Expense</a></li>
								<li class="active"><a href="{% url 'transactions:foreb_debt' %}">Foreb-Debt Payment</a></li>
								<li class="active"><a href="{% url 'transactions:customer_debt' %}">Customer-Debt Payment</a></li>
							</ul>
						</li>

						<li>
							<a><span><i class="fa fa-check-square-o icon"></i></span>Approve Transactions</a>
							<ul class="nav nav-pills nav-stacked" id="roos">
								<li class="active"><a href="{% url 'transactions:show_sales' %}"><span class="badge pull-right">{{count_sales}}</span>Sales Transactions</a></li>
								<li class="active"><a href="{% url 'transactions:show_purchase' %}"><span class="badge pull-right">{{count_purchase}}</span>Purchase Transactions</a></li>
								<li class="active"><a href="{% url 'transactions:show_foreb' %}"><span class="badge pull-right">{{count_foreb}}</span>Forebagro Debt Payment</a></li>
								<li class="active"><a href="{% url 'transactions:show_customer' %}"><span class="badge pull-right">{{count_customer}}</span>Customer Debt Payment</a></li>
								<li class="active"><a href="{% url 'transactions:show_expense' %}"><span class="badge pull-right">{{count_expense}}</span>Expense-Based Transactions</a></li>
							</ul>
						</li>

						<li>
							<a><span><i class="fa fa-eye fa-lg icon"></i></span>Report</a>
							<ul class="nav nav-pills nav-stacked" id="">
								<li class="active"><a href="{% url 'transactions:view_summary' %}">Summary</a></li>
								<li class="active"><a href="{% url 'transactions:view_customer_statement' %}">Customer Statement</a></li>
							</ul>
						</li>

						<!--<li>-->
						<!--	<a href="{% url 'constants:list' %}"><span><i class="fa fa-stack-overflow icon"></i></span>Constants</a>-->
						<!--</li>-->
					</ul>
					<footer>
						Foreb Agro Products Nig. Ltd<br>
						Contact Number: 07036470803<br>
						<span id="datetime"></span>
					</footer>
				</div>
			</div><!--end of left column-->

			<div class="col-sm-9 col-right col">
				<header id='headers' class="header">
                  <div class="button pull-right">
                      <a href="{% url 'accounts:logout' %}" title="Logout" class="label label-primary" id="logout-btn">Log out</a>
				  </div>
					<div class="welcome">
						<p id="welcome"><i>Welcome, </i><span class="label" id="username">{{ user.username }}</span></p>
						<p><strong><span class="label label-primary" id="email">{{ user.email }}</span></strong></p>
					</div>
				</header>

				<div id="body-content" class="padding" style="margin-top:-15px">
					<div class="message-container">
					</div>
					<div id="content">
						{% block content%}
						{% endblock content%}
					</div>
				</div>

			</div> <!--end of right column-->

		</div><!--end of row-->
	</div><!--end of container-->
	</section>

	<section class="empty">
	  <div class="container">
        <p> &nbsp;</p>
      </div>
    </section>

	<section class="footer">
      <div class="container">
        <p id="copyright" class="copyright"> Copyright &copy; 2020 Forebagro Products Nig. Ltd</p>
      </div>
    </section>
</body>
</html>

ForebAgro/templates/contact.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap3 %}
<html lang="en" dir="ltr">
  <head>
  <meta name="viewport" content="width=device-width" initial-scale=1>
  <meta http-equiv="x-ua-compatible" content="IE=edge">
  <title>Forebagro</title>
  <link rel="short icon" type="image/png" href="{% static 'images/favicon.png' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome-4.7.0/css/font-awesome.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
  <link href='https://fonts.googleapis.com/css?family=Alata' rel='stylesheet'>
  <script type="text/javascript" src="{% static 'js/script.js' %}" defer></script>
    <style>
    .contact
    {
      position: relative;
      min-height: 100vh;
      padding: 50px 100px;
      display: flex;
      justify-content: center;
      margin-top: -20px;
      align-items: center;
      flex-direction: column;
      background-image: url(images/globe.jpg);
      background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.9)), url("{% static 'images/kernel.jpg' %}");
      background-size: cover;
    }
    </style>
  </head>
  <body>
    <nav class="navbar">
      <div class="brand-title"><span><a href="{% url 'home' %}"><img class="logo" src= "{% static 'images/foreblogo.png' %}"></a></span></div>
      <a href="#" class="toggle-button">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
      </a>
      <div class="navbar-links">
        <ul style="font-family: 'Alata';">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'about' %}">About Us</a></li>
          <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>
      </div>
    </nav>
    <section class="contact">
      <div class="content">
        <h2 style="font-size: 40px;font-family: 'Alata';font-weight:lighter;color: #fff">Contact <span style="color:#89c227;">Us</span></h2>
        <p style="font-size: 16px;font-family: 'Alata';font-weight:lighter;">Please use this form for inquiries, order requests, or to give us feedback on our products and services.</p>
      </div>
      <div class="contact-container">
        <div class="contactInfo">
          <div class="box">
            <div class="icon"><i style="color:white" class="fa fa-map-marker" aria-hidden="true"></i></div>
            <div class="text">
              <h3 style="font-family: 'Alata';">Address</h3>
              <p style="font-family: 'Alata';">Head Office & Factory Plots 2 & 3,<br>Block Q Ilesa Road, Government Industrial Estate,<br>Akure, Ondo State.</p>
            </div>
          </div>
          <div class="box">
            <div class="icon"><i class="fa fa-phone" style="color:white" aria-hidden="true"></i></div>
            <div class="text">
              <h3 style="font-family: 'Alata';">Phone</h3>
              <p style="font-family: 'Alata';">(+234) 8174620250 | (+234) 8174620243</p>
            </div>
          </div>
          <div class="box">
            <div class="icon"><i class="fa fa-envelope-o" style="color:white" aria-hidden="true"></i> </div>
            <div class="text">
              <h3 style="font-family: 'Alata';">Email</h3>
              <p style="font-family: 'Alata';">info@forebagroproducts .com | sales@forebagroproducts.com</p>

            </div>
          </div>
        </div>
        <div class="contactForm">
          <form method="post" action="{% url 'contact:send' %}">
             {% if messages %}
    <ul class="messagelist">
        {% for message in messages %}
            <li>{{ message.message }}</li>
        {% endfor %}
    </ul>
{% endif %}
            <h1 style="font-family: 'Alata';color:#89c227;">Send Message</h1>
               {% csrf_token %}
               {% bootstrap_form form %}
            <div class="inputBox">
              <input type="submit" name="" value="Send">
            </div>
          </form>
        </div>
      </div>
    </section>

  <section class="footer" >
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <img src="{% static 'images/foreblogo.png' %}" alt="" class="footer-logo">
            <p>Address:
              Head Office & Factory
              Plots 2 & 3, Block Q Ilesa Road,
              Government Industrial Estate,
              Akure, Ondo State</p>
          </div>

          <div class="col-md-4">
            <h4 style="font-family: 'Alata';">Quick Contact</h4>
            <p><i class="fa fa-phone-square"></i> (+234) 8174620250 | (+234) 8174620243</p>
            <p><i class="fa fa-envelope"></i> info@forebagroproducts.com | sales@forebagroproducts.com</p>
            <p><i class="fa fa-whatsapp"></i> (+234) 8035092513</p>
            <p><i class="fa fa-home"></i> Akure, Ondo State, Nigeria</p>
          </div>
          <div class="col-md-4">
            <h4 style="font-family: 'Alata';">Follow Us On</h4>
            <p><i class="fa fa-facebook-official"></i> Facebook</p>
            <p><i class="fa fa-linkedin-square"></i> Linkedin</p>
            <p><i class="fa fa-twitter"></i> Twitter</p>
          </div>
        </div><hr>
        <p class="copyright"> Copyright &copy; 2020 Forebagro Products Nig. Ltd</p>
      </div>
      <a class="gotopbtn" href="#"><i class="fa fa-arrow-up"></i></a>
    </section>
  </body>
</html>