ForebAgro/Forebagro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [
                url(r"^$", views.HomePage.as_view(), name="home"),
                url(r"^about-us/$", views.AboutPage.as_view(), name="about"),
                url(r"^contact-us/$", views.ContactPage, name="contact"),
                url(r"^app/", include('accounts.urls', namespace="accounts")),
                url(r"^admin/", admin.site.urls),
                url(r"^accounts/", include("django.contrib.auth.urls")),
                url(r'^clientele/', include("clientele.urls", namespace="clientele")),
                url(r'^contact/', include("contact.urls", namespace="contact")),
                url(r'^transactions/', include("transactions.urls", namespace="transactions")),
                url(r'^products/', include("products.urls", namespace="products")),
                url(r'^constants/', include("constant.urls", namespace="constants")),
]

ForebAgro/contact/urls.py
from django.conf.urls import url, include, url
from contact import views

urlpatterns = [
    url(r'^contact-us/$', views.send, name='send'),
]

ForebAgro/transactions/urls.py
from django.conf.urls import url
from . import views

app_name = 'transactions'

urlpatterns = [
                url(r'^record_expense/$', views.record, name='record_expense'),
                url(r'^customer_debt/$', views.customer, name='customer_debt'),
                url(r'^foreb_debt/$', views.foreb, name='foreb_debt'),
                url(r'^purchase/$', views.purchase, name='purchase'),
                url(r'^sales/$', views.sales, name='sales'),

                url(r'^customer_transactions/$', views.showcustomer, name='show_customer'),
                url(r'^foreb_transactions/$', views.showforeb, name='show_foreb'),
                url(r'^sales_transactions/$', views.showsales, name='show_sales'),
                url(r'^purchase_transactions/$', views.showpurchase, name='show_purchase'),
                url(r'^expense_transactions/$', views.showexpense, name='show_expense'),

                url(r'^customer-transactions/$', views.showcustomer_user, name='show_customer_user'),
                url(r'^foreb-transactions/$', views.showforeb_user, name='show_foreb_user'),
                url(r'^sales-transactions/$', views.showsales_user, name='show_sales_user'),
                url(r'^purchase-transactions/$', views.showpurchase_user, name='show_purchase_user'),
                url(r'^expense-transactions/$', views.showexpense_user, name='show_expense_user'),

                url(r'^sales_details/(?P<id>\d+)/$', views.sales_details, name='sales_details'),
                url(r'^purchase_details/(?P<id>\d+)/$', views.purchase_details, name='purchase_details'),
                url(r'^foreb_details/(?P<id>\d+)/$', views.foreb_details, name='foreb_details'),
                url(r'^customer_details/(?P<id>\d+)/$', views.customer_details, name='customer_details'),
                url(r'^expense_details/(?P<id>\d+)/$', views.expense_details, name='expense_details'),

                url(r'^approve_sales/(?P<id>\d+)/$', views.sales_approve, name='approve_sales'),
                url(r'^approve_purchase/(?P<id>\d+)/$', views.purchase_approve, name='approve_purchase'),
                url(r'^approve_foreb/(?P<id>\d+)/$', views.foreb_approve, name='approve_foreb'),
                url(r'^approve_customer/(?P<id>\d+)/$', views.customer_approve, name='approve_customer'),
                url(r'^approve_expense/(?P<id>\d+)/$', views.expense_approve, name='approve_expense'),

                url(r'^view-summary/$', views.view_summary, name='view_summary'),
                url(r'^summary/$', views.summary, name='summary'),
                url(r'^view-customer-statement/$', views.view_customer_statement, name='view_customer_statement'),
                url(r'^customer-statement/$', views.customer_statement, name='customer_statement'),

                url(r'^update-sales/(?P<id>\d+)/$', views.update_sales, name='update_sales'),
                url(r'^update-expense/(?P<id>\d+)/$', views.update_expense, name='update_expense'),
                url(r'^update-purchase/(?P<id>\d+)/$', views.update_purchase, name='update_purchase'),
                url(r'^update-customer/(?P<id>\d+)/$', views.update_customer, name='update_customer'),
                url(r'^update-foreb/(?P<id>\d+)/$', views.update_foreb, name='update_foreb'),

                url(r'^delete-sales/(?P<pk>\d+)/$', views.SalesDeleteView.as_view(), name='delete_sales'),
                url(r'^delete-purchase/(?P<pk>\d+)/$', views.PurchaseDeleteView.as_view(), name='delete_purchase'),
                url(r'^delete-expense/(?P<pk>\d+)/$', views.ExpenseDeleteView.as_view(), name='delete_expense'),
                url(r'^delete-foreb/(?P<pk>\d+)/$', views.ForebDeleteView.as_view(), name='delete_foreb'),
                url(r'^delete-customer/(?P<pk>\d+)/$', views.CustomerDeleteView.as_view(), name='delete_customer'),

                url(r'^homepage/$', views.HomePage.as_view(), name="home"),
]

ForebAgro/transactions/views.py
from django.shortcuts import render, redirect
from .models import ExpenseBasedTransactionForm, ExpenseBasedTransaction, TransactionRecord, CustomerDebtTransaction, \
    CustomerDebtTransactionForm, ForebDebtTransactionForm, SalesTransaction, SalesTransactionForm, ForebDebtTransaction, \
    PurchaseTransaction, PurchaseTransactionForm
from clientele.models import Clientele
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView,
                                  UpdateView, DeleteView)
from django.http import HttpResponse, request
from .forms import SummaryForm, PTForm, SLForm, EBForm, CDForm, FDForm, CustomerForm

from constant.models import Constants
from products.models import Product
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
import datetime
from django.urls import reverse_lazy
import csv
from django.db.models import Q
from django.core import serializers


# Create your views here.

@login_required
def record(request):
    if request.method == 'POST':
        form = ExpenseBasedTransactionForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            clientele_id = form.cleaned_data['clientele_id']
            clientele_name = Clientele.objects.raw('select id,clientele_name from clientele where id=' + clientele_id)[
                0]
            try:
                numy = ExpenseBasedTransaction.objects.latest('id')
                numberofrecords = numy.id
            except:
                numberofrecords = ExpenseBasedTransaction.objects.filter().count()

            obj.clientele_name = clientele_name
            obj.status = 'Pending'
            obj.narration = str(form.cleaned_data['quantity']) + ' of ' + str(clientele_name) + ' @ ' + str(
                form.cleaned_data['rate'])
            generatednumber = int(numberofrecords) + 1
            obj.transaction_reference = 'EB-' + str(generatednumber)
            obj.transaction_type = 'expense-based transaction'
            obj.initiator = request.user.get_username()
            obj.save()

            return render(request, "transactions/eb_transaction_successful.html", )
    else:
        form = ExpenseBasedTransactionForm()

    return render(request, "transactions/eb_transaction_form.html", {"form": form, "messages": ''})


@login_required
def customer(request):
    if request.method == 'POST':
        form = CustomerDebtTransactionForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            clientele_id = form.cleaned_data['clientele_name']
            clientele_name = Clientele.objects.raw('select id,clientele_name from clientele where id=' + clientele_id)[
                0]
            obj.clientele_id = clientele_id
            obj.clientele_name = clientele_name
            obj.status = 'Pending'

            try:
                numy = CustomerDebtTransaction.objects.latest('id')
                numberofrecords = numy.id
            except:
                numberofrecords = CustomerDebtTransaction.objects.filter().count()

            generatednumber = int(numberofrecords) + 1
            obj.transaction_reference = 'CD-' + str(generatednumber)
            obj.transaction_type = 'customer-debt transaction'
            obj.initiator = request.user.get_username()
            obj.save()
            return render(request, "transactions/cd_transaction_successful.html", )
    else:
        form = CustomerDebtTransactionForm()

    return render(request, "transactions/cd_transaction_form.html", {"form": form, "messages": ''})


@login_required
def foreb(request):
    if request.method == 'POST':
        form = ForebDebtTransactionForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            clientele_id = form.cleaned_data['clientele_name']
            clientele_name = Clientele.objects.raw('select id,clientele_name from clientele where id=' + clientele_id)[
                0]
            obj.clientele_id = clientele_id
            obj.clientele_name = clientele_name

            try:
                numy = ForebDebtTransaction.objects.latest('id')
                numberofrecords = numy.id
            except:
                numberofrecords = ForebDebtTransaction.objects.filter().count()

            generatednumber = int(numberofrecords) + 1
            obj.transaction_reference = 'FD-' + str(generatednumber)
            obj.status = 'pending'
            obj.transaction_type = 'foreb-debt transaction'
            obj.initiator = request.user.get_username()
            obj.save()
            return render(request, "transactions/fd_transaction_successful.html", )
    else:
        form = ForebDebtTransactionForm()

    return render(request, "transactions/fd_transaction_form.html", {"form": form, "messages": ''})


@login_required
def purchase(request):
    if request.method == 'POST':
        form = PurchaseTransactionForm(request.POST, auto_id=True, )
        if form.is_valid():
            obj = form.save(commit=False)
            clientele_id = form.cleaned_data['clientele_name']
            product_id = form.cleaned_data['product_name']
            clientele_name = Clientele.objects.raw('select id,clientele_name from clientele where id=' + clientele_id)[
                0]
            product_name = Product.objects.raw('select id,product_name from products where id=' + product_id)[0]
            obj.clientele_id = clientele_id
            obj.clientele_name = clientele_name
            obj.product_id = product_id
            obj.product_name = product_name
            product_quantity = str(form.cleaned_data['product_quantity'])
            product_rate = str(form.cleaned_data['product_rate'])

            try:
                numy = PurchaseTransaction.objects.latest('id')
                numberofrecords = numy.id
            except:
                numberofrecords = PurchaseTransaction.objects.filter().count()

            generatednumber = int(numberofrecords) + 1
            obj.transaction_reference = 'PC-' + str(generatednumber)
            obj.status = 'pending'
            obj.narration = product_quantity + "kg" + " of " + str(product_name) + " @ " + product_rate
            obj.transaction_type = 'purchase transaction'
            obj.initiator = request.user.get_username()
            obj.save()
            return render(request, "transactions/pc_transaction_successful.html", )
    else:
        form = PurchaseTransactionForm()

    return render(request, "transactions/pc_transaction_form.html", {"form": form, "messages": ''})


@login_required
def sales(request):
    if request.method == 'POST':
        form = SalesTransactionForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            clientele_id = form.cleaned_data['clientele_name']
            product_id = form.cleaned_data['product_name']
            clientele_name = Clientele.objects.raw('select id,clientele_name from clientele where id=' + clientele_id)[
                0]
            product_name = Product.objects.raw('select id,product_name from products where id=' + product_id)[0]
            product_quantity = str(form.cleaned_data['product_quantity'])
            product_rate = str(form.cleaned_data['product_rate'])
            obj.clientele_id = clientele_id
            obj.clientele_name = clientele_name
            obj.product_id = product_id
            obj.product_name = product_name

            try:
                numy = SalesTransaction.objects.latest('id')
                numberofrecords = numy.id
            except:
                numberofrecords = SalesTransaction.objects.filter().count()


            generatednumber = int(numberofrecords) + 1
            obj.transaction_reference = 'SA-' + str(generatednumber)

            obj.narration = product_quantity + "tons" + " of " + str(product_name) + " @ " + product_rate
            obj.status = 'pending'
            obj.transaction_type = 'sales transaction'
            obj.initiator = request.user.get_username()
            obj.save()
            return render(request, "transactions/sa_transaction_successful.html", )
    else:
        form = SalesTransactionForm()

    return render(request, "transactions/sa_transaction_form.html", {"form": form, "messages": ''})


@login_required
def showcustomer(request):
    if 'transactions_query' in request.GET:
        transactions = CustomerDebtTransaction.objects.filter(
            clientele_name__icontains=request.GET['transactions_query'])
    else:
        transactions = CustomerDebtTransaction.objects.filter(status__icontains='pending')[:20]

    return render(request, "approve/customer_list.html", {"transactions": transactions, "messages": ''})


@login_required
def showforeb(request):
    if 'transactions_query' in request.GET:
        transactions = ForebDebtTransaction.objects.filter(clientele_name__icontains=request.GET['transactions_query'])
    else:
        transactions = ForebDebtTransaction.objects.filter(status__icontains='pending')[:20]

    return render(request, "approve/foreb_list.html", {"transactions": transactions, "messages": ''})


@login_required
def showsales(request):
    if 'transaction_query' in request.GET:
        transactions = SalesTransaction.objects.filter(clientele_name__icontains=request.GET['transaction_query'])
    else:
        transactions = SalesTransaction.objects.filter(status__icontains='pending')[:20]

    return render(request, "approve/sales_list.html", {"transactions": transactions, "messages": ''})


@login_required
def showpurchase(request):
    if 'transactions_query' in request.GET:
        transactions = PurchaseTransaction.objects.filter(clientele_name__icontains=request.GET['transactions_query'])
    else:

ForebAgro/transactions/templates/approve/approve_expense.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}

	{% csrf_token %}
	<div class="content-wrapper">
		<div name="content">
			<div class="head">
				<div class="row">
					<div class="col-sm-7 title" >
						<span class="fa fa-circle-info "></span>Transaction Details

					</div>

				</div>
			</div>

			<div class="content padding table-responsive">

				<table class="transaction-detail">

					<tr>
						<th width="150px"><h4><span class="label label-primary">Clientele Name</span></h4></th>
						<td><strong>: {{transactions.clientele_name}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Transaction Ref.</span></h4></th>
						<td><strong>: {{transactions.transaction_reference}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Total Cost</span></h4></th>
						<td><strong>: &#8358; {{transactions.total_cost}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">narration</span></h4></th>
						<td><strong>: {{transactions.narration}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Rate</span></h4></th>
						<td><strong>: {{transactions.rate}}</strong></td>
					</tr>
                    	<tr>
						<th><h4><span class="label label-primary">Quantity</span></h4></th>
						<td><strong>: {{transactions.quantity}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Date Initiated</span></h4></th>
						<td><strong>: {{transactions.date_initiated}}</strong></td>
					</tr>
				</table>
				<br><br><hr>
					<a href="{% url 'transactions:show_expense' %}" class="btn btn-danger"><i class="fa fa-remove fa-lg white" aria-hidden="true"></i> Reject</a>
					<a href="{% url 'transactions:approve_expense' id=transactions.id %}" class="btn btn-primary"><i class="fa fa-check-circle white fa-lg" aria-hidden="true"></i> Approve</a>

			</div>

		</div> <!-- end of content -->
	</div> <!--end of content-wrapper -->



<script type="text/javascript">
		$(document).ready(function(){
			$(".form-control").css({'height': '32px', 'width': '500px'});
			$("#tab")..css({'width': '600px', 'margin-left': '70px'});
			$(".wrapper").css({'justify-content': 'center', 'display': 'flex'});
			$("th").css({'font-size': '20px'});
</script>
{% endblock content %}

ForebAgro/transactions/templates/approve/approve_foreb.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}

	{% csrf_token %}
	<div class="content-wrapper">
		<div name="content">
			<div class="head">
				<div class="row">
					<div class="col-sm-7 title" >
						<span class="fa fa-user"></span>Transaction Details

					</div>

				</div>
			</div>

			<div class="content padding table-responsive">

				<table class="transaction-detail">

					<tr>
						<th width="150px"><h4><span class="label label-primary">Clientele Name</span></h4></th>
						<td><strong>: {{transactions.clientele_name}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Transaction Ref.</span></h4></th>
						<td><strong>: {{transactions.transaction_reference}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Amount Paid</span></h4></th>
						<td><strong>: &#8358; {{transactions.amount_paid}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">narration</span></h4></th>
						<td><strong>: {{transactions.narration}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Comments</span></h4></th>
						<td><strong>: {{transactions.comments}}</strong></td>
					</tr>
					<tr>
						<th><h4><span class="label label-primary">Date Initiated</span></h4></th>
						<td><strong>: {{transactions.date_initiated}}</strong></td>
					</tr>
				</table>
				<br><br><hr>
					<a href="{% url 'transactions:show_foreb' %}" class="btn btn-danger"><i class="fa fa-remove fa-lg white" aria-hidden="true"></i> Reject</a>
					<a href="{% url 'transactions:approve_foreb' id=transactions.id %}" class="btn btn-primary"><i class="fa fa-check-circle white fa-lg" aria-hidden="true"></i> Approve</a>

			</div>

		</div> <!-- end of content -->
	</div> <!--end of content-wrapper -->



<script type="text/javascript">
		$(document).ready(function(){
			$(".form-control").css({'height': '32px', 'width': '500px'});
			$("#tab").css({'width': '600px', 'margin-left': '70px'});
			$(".wrapper").css({'justify-content': 'center', 'display': 'flex'});
			$("th").css({'font-size': '20px'});
</script>
{% endblock content %}

ForebAgro/transactions/templates/approve/customer_list.html
{% extends "base.html" %}

{% load static %}

{% block javascript %}
{% endblock %}
{% block content %}

<div class="content-wrapper">
	<div class="content">
		<div class="head">
			<div class="row">
				<div class="col-sm-8 title" >
					<span class="fa fa-book"></span>Customer-Debt Transactions List
				</div>
				<div class="col-sm-4">
					<form>
						<div class="input-group search-box" style="margin-top:-5px;margin-bottom:-120px">
							<input type="text" class="form-control" name="transaction_query" placeholder="Search for Transaction">
						      <span class="input-group-btn">
						        <button class="btn btn-default" type="submit"><i class="fa fa-search fa-fw"></i></button>
						      </span>
						</div>
					</form>
				</div>
			</div>
		</div>

		<div class="content padding table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Clientele Name</th>
						<th>Narration</th>
						<th>Status</th>
						<th><center>Actions</center></th>
					</tr>
				</thead>
				<tbody>

					{% for t in transactions %}
						<tr>
							<td><b>{{forloop.counter}}</b>. {{ t.clientele_name }}</td>
							<td>{{ t.narration }}</td>
							<td>{{ t.status }}</td>
							<td class="action-container" align="center">

								<a href="{% url 'transactions:customer_details' id=t.id %}"  class="btn btn-warning btn-sm action" title="View Transaction">
									<span class="fa fa-eye fa-lg"></span> View
								</a>
							</td>
						</tr>
					{%empty%}
						<tr>
							<td colspan="12312" align="center">
								<h1 class="text-danger">No pending transactions!</h1>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div> <!-- end of content -->
</div> <!--end of content-wrapper -->
{% endblock content %}

ForebAgro/transactions/templates/approve/expense_list.html
{% extends "base.html" %}

{% load static %}

{% block javascript %}
{% endblock %}
{% block content %}

<div class="content-wrapper">
	<div class="content">
		<div class="head">
			<div class="row">
				<div class="col-sm-8 title" >
					<span class="fa fa-book"></span>Expense-Based Transactions List
				</div>
				<div class="col-sm-4">
					<form>
						<div class="input-group search-box" style="margin-top:-5px;margin-bottom:-120px">
							<input type="text" class="form-control" name="transaction_query" placeholder="Search for Transaction">
						      <span class="input-group-btn">
						        <button class="btn btn-default" type="submit"><i class="fa fa-search fa-fw"></i></button>
						      </span>
						</div>
					</form>
				</div>
			</div>
		</div>

		<div class="content padding table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Clientele Name</th>
						<th>Narration</th>
						<th>Status</th>
						<th><center>Actions</center></th>
					</tr>
				</thead>
				<tbody>

					{% for t in transactions %}
						<tr>
							<td><b>{{forloop.counter}}</b>. {{ t.clientele_name }}</td>
							<td>{{ t.narration }}</td>
							<td>{{ t.status }}</td>
							<td class="action-container" align="center">

								<a href="{% url 'transactions:expense_details' id=t.id %}"  class="btn btn-warning btn-sm action" title="View Transaction">
									<span class="fa fa-eye fa-lg"></span> View
								</a>
							</td>
						</tr>
                    {%empty%}
						<tr>
							<td colspan="12312" align="center">
								<h1 class="text-danger"><i class="fa fa-frown-o" aria-hidden="true"></i> &nbsp;No pending transactions!</h1>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div> <!-- end of content -->
</div> <!--end of content-wrapper -->
{% endblock content %}

ForebAgro/transactions/templates/approve/foreb_list.html
{% extends "base.html" %}

{% load static %}

{% block javascript %}
{% endblock %}
{% block content %}

<div class="content-wrapper">
	<div class="content">
		<div class="head">
			<div class="row">
				<div class="col-sm-8 title" >
					<span class="fa fa-book"></span>Foreb-Debt Transactions List
				</div>
				<div class="col-sm-4">
					<form>
						<div class="input-group search-box" style="margin-top:-5px;margin-bottom:-120px">
							<input type="text" class="form-control" name="transaction_query" placeholder="Search for Transaction">
						      <span class="input-group-btn">
						        <button class="btn btn-default" type="submit"><i class="fa fa-search fa-fw"></i></button>
						      </span>
						</div>
					</form>
				</div>
			</div>
		</div>

		<div class="content padding table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Clientele Name</th>
						<th>Narration</th>
						<th>Status</th>
						<th><center>Actions</center></th>
					</tr>
				</thead>
				<tbody>

					{% for t in transactions %}
						<tr>
							<td><b>{{forloop.counter}}</b>. {{ t.clientele_name }}</td>
							<td>{{ t.narration }}</td>
							<td>{{ t.status }}</td>
							<td class="action-container" align="center">

								<a href="{% url 'transactions:foreb_details' id=t.id %}"  class="btn btn-warning btn-sm action" title="View Transaction">
									<span class="fa fa-eye fa-lg"></span> View
								</a>
							</td>
						</tr>
					{%empty%}
						<tr>
							<td colspan="12312" align="center">
								<h1 class="text-danger"><i style="color: #A94442" class="fa fa-frown-o fa-lg" aria-hidden="true"></i> &nbsp;No pending transactions!</h1>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div> <!-- end of content -->
</div> <!--end of content-wrapper -->
{% endblock content %}

ForebAgro/transactions/templates/approve/purchase_list.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block javascript %}
{% endblock %}
{% block content %}

<div class="content-wrapper">
	<div class="content">
		<div class="head">
			<div class="row">
				<div class="col-sm-8 title" >
					<span class="fa fa-book"></span>Purchase Transactions List
				</div>
				<div class="col-sm-4">
					<form>
						<div class="input-group search-box" style="margin-top:-5px;margin-bottom:-120px">
							<input type="text" class="form-control" name="transaction_query" placeholder="Search for Transaction">
						      <span class="input-group-btn">
						        <button class="btn btn-default" type="submit"><i class="fa fa-search fa-fw"></i></button>
						      </span>
						</div>
					</form>
				</div>
			</div>
		</div>

		<div class="content padding table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Clientele Name</th>
						<th>Transaction Cost</th>
						<th>Narration</th>
						<th>Status</th>
						<th><center>Actions</center></th>
					</tr>
				</thead>
				<tbody>

					{% for t in transactions %}
						<tr>
							<td><b>{{forloop.counter}}</b>. {{ t.clientele_name }}</td>
							<td>&#8358; {{ t.transaction_cost|stringformat:"0.2f"|intcomma }}</td>
							<td>{{ t.narration }}</td>
							<td>{{ t.status }}</td>
							<td class="action-container" align="center">

								<a href="{% url 'transactions:purchase_details' id=t.id %}"  class="btn btn-warning btn-sm action" title="View Transaction">
									<span class="fa fa-eye fa-lg"></span> View
								</a>
							</td>
						</tr>
					{%empty%}
						<tr>
							<td colspan="12312" align="center">
								<h1 class="text-danger">No pending transactions!</h1>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div> <!-- end of content -->
</div> <!--end of content-wrapper -->
{% endblock content %}

ForebAgro/transactions/templates/approve/sales_list.html
{% extends "base.html" %}

{% load static %}

{% block javascript %}
{% endblock %}
{% block content %}

<div class="content-wrapper">
	<div class="content">
		<div class="head">
			<div class="row">
				<div class="col-sm-8 title" >
					<span class="fa fa-book"></span>Sales Transactions List
				</div>
				<div class="col-sm-4">
					<form>
						<div class="input-group search-box" style="margin-top:-5px;margin-bottom:-120px">
							<input type="text" class="form-control" name="transaction_query" placeholder="Search for Transaction">
						      <span class="input-group-btn">
						        <button class="btn btn-default" type="submit"><i class="fa fa-search fa-fw"></i></button>
						      </span>
						</div>
					</form>
				</div>
			</div>
		</div>

		<div class="content padding table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Clientele Name</th>
						<th>Transaction Cost</th>
						<th>Narration</th>
						<th>Status</th>
						<th><center>Actions</center></th>
					</tr>
				</thead>
				<tbody>

					{% for t in transactions %}
						<tr>
							<td><b>{{forloop.counter}}</b>. {{ t.clientele_name }}</td>
							<td>{{ t.transaction_cost }}</td>
							<td>{{ t.narration }}</td>
							<td>{{ t.status }}</td>
							<td class="action-container" align="center">

								<a href="{% url 'transactions:sales_details' id=t.id %}"  class="btn btn-warning btn-sm" title="View Transaction">
									<span class="fa fa-eye fa-lg"></span> View
								</a>
							</td>
						</tr>
					{%empty%}
						<tr>
							<td colspan="12312" align="center">
								<h1 class="text-danger">No pending transactions!</h1>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div> <!-- end of content -->
</div> <!--end of content-wrapper -->
{% endblock content %}